config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :articles
  resources :books
  resources :answers
  resources :questions
  resources :feedbacks
  resources :comments
  resources :posts

  get '/search', to: 'posts#index'

  get '/sort_asc_title', to: 'posts#index'
  get '/sort_asc_body', to: 'posts#index'
  get '/sort_desc_title', to: 'posts#index'
  get '/sort_desc_body', to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/assemblies_part.rb
class AssembliesPart < ApplicationRecord
  belongs_to :assembly
  belongs_to :part
end

app/models/assembly.rb
class Assembly < ApplicationRecord
    has_and_belongs_to_many :parts
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :post
    has_many :poly_comments, as: :commentable
end

app/models/game.rb
class Game < ApplicationRecord
    has_one :Peak
    has_one :team, through: :peak
end

app/models/part.rb
class Part < ApplicationRecord
    has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
    belongs_to :game
    has_one :team
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :feedbacks
    has_one :question
    has_many :poly_comments, as: :commentable
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :post
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :subjects
    has_many :teachers, through: :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :subjects
    has_many :studeents, through: :subjects
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :peak
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:title, :answer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_area :answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer, class: 'btn btn-success' %> |
<%= link_to 'Back', answers_path, class: 'btn btn-secondary' %>

app/views/answers/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Answers</h1>

  <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
  <table class="table table-striped" id="myTable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Answer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.title  %></td>
          <td><%= answer.answer  %></td>
          <td><%= link_to 'Show', answer, class: 'btn btn-success' %></td>
          <td><%= link_to 'Edit', edit_answer_path(answer), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Answer', new_answer_path, class: 'btn btn-secondary' %>
</div>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path, class: 'btn btn-secondary' %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_answer_path(@answer), class: 'btn btn-primary' %> |
<%= link_to 'Back', answers_path, class: 'btn btn-secondary' %>