config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :articles
  resources :books
  resources :answers
  resources :questions
  resources :feedbacks
  resources :comments
  resources :posts

  get '/search', to: 'posts#index'

  get '/sort_asc_title', to: 'posts#index'
  get '/sort_asc_body', to: 'posts#index'
  get '/sort_desc_title', to: 'posts#index'
  get '/sort_desc_body', to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/assemblies_part.rb
class AssembliesPart < ApplicationRecord
  belongs_to :assembly
  belongs_to :part
end

app/models/assembly.rb
class Assembly < ApplicationRecord
    has_and_belongs_to_many :parts
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :post
    has_many :poly_comments, as: :commentable
end

app/models/game.rb
class Game < ApplicationRecord
    has_one :Peak
    has_one :team, through: :peak
end

app/models/part.rb
class Part < ApplicationRecord
    has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
    belongs_to :game
    has_one :team
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :feedbacks
    has_one :question
    has_many :poly_comments, as: :commentable
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :post
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :subjects
    has_many :teachers, through: :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :subjects
    has_many :studeents, through: :subjects
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :peak
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:name, :rating, :message)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_area :rating %>
  </div>

  <div class="field">
    <%= form.label :Message %>
    <%= form.text_area :Message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback, class: 'btn btn-primary' %> |
<%= link_to 'Back', feedbacks_path, class: 'btn btn-secondary' %>

app/views/feedbacks/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Feedbacks</h1>

  <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
  <table class="table table-striped" id="myTable">
    <thead>
      <tr>
        <th>Name</th>
        <th>Rating</th>
        <th>Message</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @feedbacks.each do |feedback| %>
        <tr>
          <td><%= feedback.name %></td>
          <td><%= feedback.rating %></td>
          <td><%= feedback.Message %></td>
          <td><%= link_to 'Show', feedback, class: 'btn btn-success'%></td>
          <td><%= link_to 'Edit', edit_feedback_path(feedback), class: 'btn btn-secondary' %></td>
          <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Feedback', new_feedback_path, class: 'btn btn-primary' %>
</div>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path, class: 'btn btn-primary' %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_feedback_path(@feedback), class: 'btn btn-primary' %> |
<%= link_to 'Back', feedbacks_path, class: 'btn btn-secondary' %>