config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :articles
  resources :books
  resources :answers
  resources :questions
  resources :feedbacks
  resources :comments
  resources :posts

  get '/search', to: 'posts#index'

  get '/sort_asc_title', to: 'posts#index'
  get '/sort_asc_body', to: 'posts#index'
  get '/sort_desc_title', to: 'posts#index'
  get '/sort_desc_body', to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/assemblies_part.rb
class AssembliesPart < ApplicationRecord
  belongs_to :assembly
  belongs_to :part
end

app/models/assembly.rb
class Assembly < ApplicationRecord
    has_and_belongs_to_many :parts
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :post
    has_many :poly_comments, as: :commentable
end

app/models/game.rb
class Game < ApplicationRecord
    has_one :Peak
    has_one :team, through: :peak
end

app/models/part.rb
class Part < ApplicationRecord
    has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
    belongs_to :game
    has_one :team
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :feedbacks
    has_one :question
    has_many :poly_comments, as: :commentable
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :post
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :subjects
    has_many :teachers, through: :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :subjects
    has_many :studeents, through: :subjects
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :peak
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hakaseapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to 'Posts', posts_path, class: "nav-link active"%>

            <%= link_to 'Feedbacks', feedbacks_path, class: "nav-link"%>
            <%= link_to 'Questions', questions_path, class: "nav-link"%>
            <%= link_to 'Answers', answers_path, class: "nav-link"%>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
   
  <script>
    function myFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }       
      }
    }
  </script>

  <style>
    a:hover {
      background-color: transparent;
    }
  </style>
  </body>
  
</html>